### ISSUE TITLE
unresolved imports

### ISSUE THREAD

**Issue by Fawadkhanfk** [dwisiswant0/ppfuzz#25]
unresolved imports `clap::crate_authors`, `clap::crate_description`, `clap::crate_name`, `clap::crate_version`
 --> src/parser.rs:5:3
  |
5 |         crate_authors,
  |         ^^^^^^^^^^^^^ no `crate_authors` in the root
6 |         crate_description,
  |         ^^^^^^^^^^^^^^^^^ no `crate_description` in the root
7 |         crate_name,
  |         ^^^^^^^^^^ no `crate_name` in the root
8 |         crate_version,
  |         ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_name`
  --> src/parser.rs:30:4
   |
30 |             crate_name!(), "FILE", "[OPTIONS]"
   |             ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_authors`
  --> src/parser.rs:33:12
   |
33 |             .author(crate_authors!())
   |                     ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_description`
  --> src/parser.rs:34:11
   |
34 |             .about(crate_description!())
   |                    ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_name`
  --> src/parser.rs:35:10
   |
35 |             .name(crate_name!())
   |                   ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_version`
  --> src/parser.rs:36:13
   |
36 |             .version(crate_version!())
   |                      ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

warning: use of deprecated macro `load_yaml`: Deprecated in Issue #3087, maybe clap::Parser would fit your use case?
  --> src/parser.rs:27:14
   |
27 |         let yaml = load_yaml!("cli.yaml");
   |                    ^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated macro `clap::load_yaml`: Deprecated in Issue #3087, maybe clap::Parser would fit your use case?
 --> src/parser.rs:9:3
  |
9 |         load_yaml,
  |         ^^^^^^^^^

error[E0308]: mismatched types
  --> src/parser.rs:32:23
   |
32 |         let app = App::from(yaml)
   |                             ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
warning: `ppfuzz` (lib) generated 2 warnings
error: could not compile `ppfuzz` due to 7 previous errors; 2 warnings emitted

**Comment by Hamada369** [comment]
same error sice a bunch of time

**Comment by MedoX71T** [comment]
error[E0432]: unresolved imports `clap::crate_authors`, `clap::crate_description`, `clap::crate_name`, `clap::crate_version`
 --> src/parser.rs:5:3
  |
5 |         crate_authors,
  |         ^^^^^^^^^^^^^ no `crate_authors` in the root
6 |         crate_description,
  |         ^^^^^^^^^^^^^^^^^ no `crate_description` in the root
7 |         crate_name,
  |         ^^^^^^^^^^ no `crate_name` in the root
8 |         crate_version,
  |         ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_name`
  --> src/parser.rs:30:4
   |
30 |             crate_name!(), "FILE", "[OPTIONS]"
   |             ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_authors`
  --> src/parser.rs:33:12
   |
33 |             .author(crate_authors!())
   |                     ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_description`
  --> src/parser.rs:34:11
   |
34 |             .about(crate_description!())
   |                    ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_name`
  --> src/parser.rs:35:10
   |
35 |             .name(crate_name!())
   |                   ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_version`
  --> src/parser.rs:36:13
   |
36 |             .version(crate_version!())
   |                      ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

warning: use of deprecated macro `load_yaml`: Deprecated in Issue #3087, maybe clap::Parser would fit your use case?
  --> src/parser.rs:27:14
   |
27 |         let yaml = load_yaml!("cli.yaml");
   |                    ^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated struct `clap::App`: Replaced with `Command`
 --> src/parser.rs:4:3
  |
4 |         App,
  |         ^^^

warning: use of deprecated macro `clap::load_yaml`: Deprecated in Issue #3087, maybe clap::Parser would fit your use case?
 --> src/parser.rs:9:3
  |
9 |         load_yaml,
  |         ^^^^^^^^^

warning: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/parser.rs:32:13
   |
32 |         let app = App::from(yaml)
   |                   ^^^

error[E0308]: mismatched types
  --> src/parser.rs:32:23
   |
32 |         let app = App::from(yaml)
   |                             ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`                                                               

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
warning: `ppfuzz` (lib) generated 4 warnings
error: could not compile `ppfuzz` due to 7 previous errors; 4 warnings emitted
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by brutexploiter** [comment]
Compiling ppfuzz v1.0.1
error[E0432]: unresolved imports `clap::crate_authors`, `clap::crate_description`, `clap::crate_name`, `clap::crate_version`
 --> /home/anonymous/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:5:3
  |
5 |         crate_authors,
  |         ^^^^^^^^^^^^^ no `crate_authors` in the root
6 |         crate_description,
  |         ^^^^^^^^^^^^^^^^^ no `crate_description` in the root
7 |         crate_name,
  |         ^^^^^^^^^^ no `crate_name` in the root
8 |         crate_version,
  |         ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_name`
  --> /home/anonymous/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:30:4
   |
30 |             crate_name!(), "FILE", "[OPTIONS]"
   |             ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_authors`
  --> /home/anonymous/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:33:12
   |
33 |             .author(crate_authors!())
   |                     ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_description`
  --> /home/anonymous/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:34:11
   |
34 |             .about(crate_description!())
   |                    ^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_name`
  --> /home/anonymous/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:35:10
   |
35 |             .name(crate_name!())
   |                   ^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: cannot determine resolution for the macro `crate_version`
  --> /home/anonymous/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:36:13
   |
36 |             .version(crate_version!())
   |                      ^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
  --> /home/anonymous/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-1.0.1/src/parser.rs:32:23
   |
32 |         let app = App::from(yaml)
   |                   --------- ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`
   |                   |
   |                   arguments to this function are incorrect
   |
note: associated function defined here

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `ppfuzz` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ppfuzz v1.0.1`, intermediate artifacts can be found at `/tmp/cargo-install1Uu14p`

**Comment by dwisiswant0** [comment]
This issue packed on [v1.0.2](https://github.com/dwisiswant0/ppfuzz/releases/tag/v1.0.2).
