### ISSUE TITLE
value: Timeout

### ISSUE THREAD

**Issue by remonsec** [dwisiswant0/ppfuzz#9]
Can you help me to fix this error 
Thanks 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Timeout', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ppfuzz-0.0.1/src/browser.rs:23:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

![Capture](https://user-images.githubusercontent.com/54717234/124393165-04d73400-dd1b-11eb-9643-1e8ea1a4a604.PNG)

**Comment by mattsse** [comment]
This means launching the browser (the chromium instance) failed.
Can you check that you have chromium installed and it's available in $PATH?
Please check also the language settings, it currently works only with english language settings of chromium, because it tries to parse the debug port from the terminal output of chromium in english language

**Comment by dwisiswant0** [comment]
Also please run with `RUST_BACKTRACE=1 ppfuzz...` to get the details, @remonsec.
